language: go
go:
- 1.15
services:
- docker
env:
  global:
  - secure: CcEkvS77LPEggqePiWNh0Iw575C/QexFymS90bfax9jOFcmBSuIpZYUFgB3ujJnMZshhF/NuqW0FPhoG4D7nZFU/aUqklJnTxoeszLtjr4l2rgGL5Zast7p1tsCABtaVq2l2Fcv8+QZDeosBqbc/OIRJBhoYc7Z7/CzQiEdmfVmihojIpUI2pRThEDkoFTY0MHsd1OL2Iey/lexGM34CDZqf7aVDcUhx8A9DdfBQn1RAL3eU/0mwoUK0j6UNSB+KzQvg0eoeCrRYJPaq5hJqiQHlPDPV4rnMsAy/MFOecMkIWk5P43TqctSb7cwWunUIVnMsRsOcqEo0bUZnGyQmmvuDJyzWSSBbnbVeKHxuue5xAOuUgRV8YauyED4GaOhtt/F+YIA4oqgb6ZUf5vKFZG1t4ibo1Db+sT1hb0m1riU6Nb1vqK5ZSWZMm8YA/NUlArH7olwuvEOW58Ayt+dg+rvAtghCLPi1LW/aaAuUlulNaqNIdTr6HwP2taXBqgp0XVz5PRlH80EtSiM3jevUCxkRys9PgmwsC3dhtHTW6FQvyPxcCTknxSQRMwtJCZhEGGJfu0NjJDbX6afVi9ELueyZehbGPTzE8zLoUb6X8DCe1vzgztqwKWlBbwhAJAvXGAadeXNqYFx5gzj309OwXX9+i0ZeostPuPlkfyFjIAw=
  - secure: CigdsFUEZhcGv6MCmihRgEFrMSA4cQRGtfITCKiZjUkDbdHiIIqX/VRiGXWLZmrCITWPXB7weZPzMgUK1U7SNZmdzUzp7RIfMKGSqJ/H++5siD22lrz1sHkrF5KGIwwKOuIU/2En+uqYHUe039awsL2GNHpghJDng6vOnOkQaq7gYVQvjlT4Qyg+I9jSfMl1nHy1viRGGpLfDQaA5sDZ3PFRSQw/NVdv34OdKzt4kTSmygx6Dl3PjRrmq1lEFaQDFJyIunwYQF0CEHL8ZirbKa8eNXqEIX/iUd/b0KrHhVZWwAJfYn/8IcWc2eImlU0OYSoCGrHqj4r2BAOReBO3KEfPNaW5D2V4Ke76BV/BtMPTLmFvBey7opxhhOTdzVENvq3DJtCpL9tAqJl4YWYFo/axas28D3nQ6w8UE5ZzBCTHvFqh1lsQhnF1iRtW6dC23ooohberTuMP4qms5pEX6Zd59477SXY40TdW+tBnhh+jHQ9EKO5UzpvaTo9sprEYNIRb55RFBjEbxco9S68EHbE8Ne/EiAu5BuxIduHpCd5+toGtKnIXvXzYW9ZfwZ0J1WBgNoyDnIQ6xsQzdj7oWmtzf/4KYuDpgzhpr4iVH5ZS1++3/O/IUwB5p692Yc8En2+Xd8/Crt0TskEIg7lT4bzj0FrByhoanhSd0LgXiaI=
  - secure: ba315hdq4wDdRS7oyDsbxIzidxViOvxDgdcDbcUIhWLtq6yihoNBJEo6O7jojQkG36E5CmpyOupLZIn0fAbrV3pWxlMkVSjb0gRVvc0cW2rT5ii2ShJ59dptQ/+aWEL3BQMkhH7EPT6ZWmkIJRPzEjpTD2kZWDkwdfA9/RFDhuemml8QDsIEbPx78/RH2+fhxGTpldbUJY2WFGvl+/zTNfdLXZGy0/bJy9aRdH/Y2eIYwwklt6csPNK6xX/r0bayFsfLqhxxLA/j7jIXYn3ccG0eQr+AKEp2bsSvZt0jsOJb+G2cJAkf1rN1UC/38ZS0GSVv8n/P8RyexHX8stIMknUSSgJ42xSPJv5LqZcjrKQMHw1c9lqMRYZJ18628URjlQRyFus+OS9vu7zIlKfaj6FluZopug0uQEbJlyw0AgB76vCaI5AGagCbEHGMiE+/5xlrzuZtQyt/nOhZNJtkMAHMoOSUhLPknGUD+AoDpiJIZWLZEL6Sg2vsf46vUcgrHZknwxjSqBhHVl/r+/gY6vRWeuDT1LcmuqsAb1CaAo1iKj27FGFWYZCslPnwm8X9pOgOr6d6shxZxDEY2XRj6dg//MXpKX1dk40j1PyhSlHNRL4sVeSyYA5jri/f7a6WPaNOX6+yuYaFi8qMGQyRr2CcrikW8v1LuWLDgKz3EDs=
  - secure: QbMyM7JdACTrjLk/R/zh12hMJX0JLc4nCqD5fipDqzFs+Uen4keie7Nr2Mx5i84MGVQwAlbsuKfefi4JQPLrJvSy0U6/Szi7ZKcUGI0ThfTH3ndM3eY0LDG76JEb65mZ8co+0zwwbd9OPSZm/8JL3o4qC00kKHCgserFnDZZ42VbzKvmEu0dXDhmZ2f8oqy9dBzVqcB8FwqIvrnpgV7zyFyScc81mNx6KFcKEJqQ3pSfDFWqWPfJfX0GUhJcMhEsN2hQBBpCFsu/zfAxuOIWK2qrTLzT93UsIr+BcDxcg88XWvHHLNfFuyUC21UBmvOnREbD8deO5r1RKTGaoHTUOJKa6+1Ra8VOem6/Wr25EcqpHb+sU4ctULWFoOV+rnqgHLUrxUKlwZuiyPBkvtlqq5A8HCb2uk/uDIMEZu9XBcof2sYzBi2Qkh6SYLPfuUpR8MJrSst/z8dGuJkU6RmcvKuMZ2FT5Niac9reQLzQ2hPqBN2A6QS7NMQo4qco/jzrtNdFa3svensExSXbCxLFJ6VuPb4wccaUHGciHWGV4bLQGVphgV9PQj/Ug3nJtNOZt+rJoe9sNbIFH4JeoGzYimsVyKREz1SE/C1DcpCQB/hNKPTJPP7TcIIYs6wCeRlOUZYRtKUb8jJS314eWeDWUU0RWPryqSDPcAd7d3r2fYk=
jobs:
  include:
  - stage: build
    name: Build
    script:
    - make build
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    deploy:
    - provider: releases
      skip_cleanup: true
      token:
        secure: hKmB6ePgt03MFd6pxoGor4ero/1RZRxJwIt9LEQjshsegREcX7fjxGlc4cUwBfwIrZdfFccePvmJ7/QwmhnZ7GTd9A8lI+tVp1StMieVwTEHmFJLl8n5tevC8t8ZMzmAjnYanB5kujGYpfdh8EL34TAbUkpJ1lQqMbsyQuJcQ415raJAxUqL5sIiymloNtPF3ocSlU3eCIw9UEY7qNB/ujZF54vZ/iIUbg/pdLLI9Xb9D/m7YiwA1IaIXasQ9HBisV1Zz6CTc3zsniQPjdVBO+g7OklWx3NNxpYvRznPh3brollqeXtVE6C71Y8V4TaHgE9DBtCyWXv+pE7wWc2wl/INN/32kPgLorV9LwOtQ73xzAWuAIbdxR+z8K+CyE0Un7L4B3Y5AH0qnfNsbs6GEj4EhsR67ePX5DFT1tM1AGS7QrbBHAtkxEDDP5ITf4TByOrs5Lx3KmG7VI4ci3XPZTtuP8pNV2cmInMb3c+zqPv6192DPk1MADccZyAFr8ekdpxNHjzXuoYZ9spOyIT7KgACBXHpcARnARjKmMyB4XCosjf2oKNZCxuJ/1123r0AtMnSd1QIJsDS+uh6DjaTqcgvO53aXMcsn0OC8GUiF73VF6WBfD2we9qjN++RLmC5mhcdJzJlrzecJhPuVL0lCqYZQhCd8qps/ERhButFRjw=
      name: squealer $TRAVIS_TAG
      file:
      - bin/squealer.darwin.amd64.$TRAVIS_TAG
      - bin/squealer.linux.amd64.$TRAVIS_TAG
      on:
        repo: owenrumney/squealer
        tags: true
  - stage: publish image
    name: Publish Docker image
    if: tag IS NOT blank
    before_script:
    - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    script:
    - make image
    - make push-image
